# Generated by Django 3.2.16 on 2022-11-23 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 23, 19, 12, 23, 660955))),
            ],
        ),
    ]
