# Generated by Django 3.2.16 on 2022-11-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='created_on',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 11, 23, 20, 2, 41, 710679)),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
