# Generated by Django 3.2.16 on 2022-11-30 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20221123_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Фидбэки', 'verbose_name_plural': 'Фидбэк'},
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
