# Generated by Django 3.2.16 on 2022-11-09 20:00

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание должно быть больше,чем из 2х слов и содержать слова "превосходно, роскошно" ', validators=[catalog.validators.validate_must_be_param], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(help_text='Загрузите картинку', null=True, upload_to='photo/%Y/%m', verbose_name='Изображение'),
        ),
    ]
