# Generated by Django 3.2.16 on 2022-11-02 19:21

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='Значене должно быть больше 0')])),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(default='1', max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('weight', models.IntegerField(default=100, validators=[catalog.validators.validate_category_weight])),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='Значене должно быть больше 0')])),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(default='1', max_length=150)),
                ('slug', models.SlugField(default='1', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='Значене должно быть больше 0')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='1', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='1', validators=[catalog.validators.validate_item_text]),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(default='1', to='catalog.Tag'),
        ),
    ]
